//
//  CaseActivityReport.swift
//  maxmailin
//
//  The forensic investigator's end-of-day artifact: a one-click daily
//  activity report for the case — every audit-chained action taken on a
//  chosen day, grouped by kind, with the chain's integrity verdict — ready
//  to paste or file into the case record. Generating the report is itself
//  logged, so the case history shows the reporting too.
//

import Foundation

enum CaseActivityReportBuilder {

    struct Inputs {
        var documentNumber: String? = nil
        var caseNumber: String = ""
        var examiner: String = ""
        var day: Date = .distantPast
        /// All audit entries; the builder selects the day's slice itself so
        /// callers can't accidentally pre-filter with a different calendar.
        var auditEntries: [(timestamp: Date, sequence: Int, action: String, detail: String, examiner: String)] = []
        var chainVerified: Bool? = nil   // nil = not checked
        var calendar: Calendar = .current
    }

    /// Plain-text report for the given day. Deterministic for testing.
    static func build(_ i: Inputs) -> String {
        let dayFmt = DateFormatter()
        dayFmt.dateStyle = .full
        dayFmt.calendar = i.calendar
        let timeFmt = DateFormatter()
        timeFmt.timeStyle = .medium
        timeFmt.calendar = i.calendar

        let dayEntries = i.auditEntries
            .filter { i.calendar.isDate($0.timestamp, inSameDayAs: i.day) }
            .sorted { $0.timestamp < $1.timestamp }

        var out = "DAILY ACTIVITY REPORT\n"
        out += "=====================\n"
        if let doc = i.documentNumber { out += "Document:  \(doc)\n" }
        out += "Case:      \(i.caseNumber.isEmpty ? "(no case number set)" : i.caseNumber)\n"
        out += "Examiner:  \(i.examiner.isEmpty ? "(not set)" : i.examiner)\n"
        out += "Date:      \(dayFmt.string(from: i.day))\n"
        switch i.chainVerified {
        case true?:  out += "Audit chain: VERIFIED — every entry's hash links to the previous entry\n"
        case false?: out += "Audit chain: FAILED VERIFICATION — the log shows signs of tampering\n"
        case nil:    out += "Audit chain: not verified for this report\n"
        }
        out += "\nACTIONS (\(dayEntries.count))\n"
        if dayEntries.isEmpty {
            out += "  No audit-logged actions on this day.\n"
        }
        for entry in dayEntries {
            out += "  [\(timeFmt.string(from: entry.timestamp))] #\(entry.sequence) \(entry.action)"
            if !entry.detail.isEmpty { out += " — \(entry.detail)" }
            if !entry.examiner.isEmpty { out += " (by \(entry.examiner))" }
            out += "\n"
        }

        // Summary by action kind (first clause of the action string).
        var counts: [String: Int] = [:]
        for entry in dayEntries {
            let kind = entry.action.components(separatedBy: ":").first ?? entry.action
            counts[kind, default: 0] += 1
        }
        if !counts.isEmpty {
            out += "\nSUMMARY\n"
            for (kind, count) in counts.sorted(by: { $0.value > $1.value }) {
                out += "  \(kind): \(count)\n"
            }
        }
        out += "\nGenerated by mailin — all records kept on-device.\n"
        return out
    }
}
