//
//  ReportBuilderView.swift
//  mailin
//
//  Configurable report builder with PDF generation via Core Graphics.
//

import SwiftUI
import NaturalLanguage
#if os(macOS)
import AppKit
#endif

// MARK: - Report Section Model

struct ReportSection: Identifiable, Hashable {
    let id: UUID
    let name: String
    let icon: String
    var isEnabled: Bool

    init(id: UUID = UUID(), name: String, icon: String, isEnabled: Bool = true) {
        self.id = id
        self.name = name
        self.icon = icon
        self.isEnabled = isEnabled
    }
}

// MARK: - Report Generator

struct ReportGenerator {

    static func generatePDF(
        title: String,
        author: String,
        sections: [ReportSection],
        emails: [MBOXParser.RawEmail],
        dateRange: ClosedRange<Date>?
    ) -> Data {
        let enabledSections = sections.filter(\.isEnabled)
        let pageWidth: CGFloat = 612
        let pageHeight: CGFloat = 792
        let margin: CGFloat = 50
        let contentWidth = pageWidth - margin * 2
        let pdfData = NSMutableData()

        #if os(macOS)
        guard let consumer = CGDataConsumer(data: pdfData as CFMutableData) else {
            return Data()
        }
        var mediaBox = CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight)
        guard let context = CGContext(consumer: consumer, mediaBox: &mediaBox, nil) else {
            return Data()
        }

        // Filter emails by date range
        let filteredEmails: [MBOXParser.RawEmail]
        if let range = dateRange {
            filteredEmails = emails.filter { email in
                guard let date = MBOXParser.parseDate(email.headers["Date"]) else { return false }
                return range.contains(date)
            }
        } else {
            filteredEmails = emails
        }

        // Title Page
        context.beginPDFPage(nil)
        var y = pageHeight - 120

        drawText(context: context, text: title, x: margin, y: y, width: contentWidth,
                 font: NSFont.systemFont(ofSize: 28, weight: .bold), color: .black, alignment: .center)
        y -= 40

        drawText(context: context, text: "by \(author)", x: margin, y: y, width: contentWidth,
                 font: NSFont.systemFont(ofSize: 16, weight: .regular), color: .darkGray, alignment: .center)
        y -= 30

        let dateFormatter = DateFormatter()
        dateFormatter.dateStyle = .long
        let dateString: String
        if let range = dateRange {
            dateString = "\(dateFormatter.string(from: range.lowerBound)) - \(dateFormatter.string(from: range.upperBound))"
        } else {
            dateString = "All emails (\(dateFormatter.string(from: Date())))"
        }
        drawText(context: context, text: dateString, x: margin, y: y, width: contentWidth,
                 font: NSFont.systemFont(ofSize: 12, weight: .regular), color: .gray, alignment: .center)
        y -= 30

        drawText(context: context, text: "Generated by mailin", x: margin, y: y, width: contentWidth,
                 font: NSFont.systemFont(ofSize: 10, weight: .light), color: .gray, alignment: .center)
        y -= 20

        drawText(context: context, text: "\(filteredEmails.count) emails analyzed", x: margin, y: y, width: contentWidth,
                 font: NSFont.systemFont(ofSize: 11, weight: .medium), color: .gray, alignment: .center)
        y -= 50

        // Table of contents
        drawText(context: context, text: "Report Sections", x: margin, y: y, width: contentWidth,
                 font: NSFont.systemFont(ofSize: 16, weight: .semibold), color: .black, alignment: .left)
        y -= 25

        for (index, section) in enabledSections.enumerated() {
            drawText(context: context, text: "\(index + 1). \(section.name)", x: margin + 20, y: y, width: contentWidth - 20,
                     font: NSFont.systemFont(ofSize: 12, weight: .regular), color: .darkGray, alignment: .left)
            y -= 18
        }

        context.endPDFPage()

        // Section Pages
        for section in enabledSections {
            context.beginPDFPage(nil)
            y = pageHeight - margin

            drawText(context: context, text: section.name, x: margin, y: y, width: contentWidth,
                     font: NSFont.systemFont(ofSize: 20, weight: .bold), color: .black, alignment: .left)
            y -= 10

            // Separator line
            context.setStrokeColor(NSColor.lightGray.cgColor)
            context.setLineWidth(0.5)
            context.move(to: CGPoint(x: margin, y: y))
            context.addLine(to: CGPoint(x: pageWidth - margin, y: y))
            context.strokePath()
            y -= 20

            let content = sectionContent(section.name, emails: filteredEmails)
            let lines = content.components(separatedBy: "\n")
            for line in lines {
                if y < margin + 30 {
                    context.endPDFPage()
                    context.beginPDFPage(nil)
                    y = pageHeight - margin
                }
                let isBold = line.hasPrefix("**")
                let cleanLine = line.replacingOccurrences(of: "**", with: "")
                let font = isBold
                    ? NSFont.systemFont(ofSize: 11, weight: .semibold)
                    : NSFont.systemFont(ofSize: 10, weight: .regular)
                let color: NSColor = isBold ? .black : .darkGray
                drawText(context: context, text: cleanLine, x: margin, y: y, width: contentWidth,
                         font: font, color: color, alignment: .left)
                y -= 16
            }

            context.endPDFPage()
        }

        context.closePDF()
        return pdfData as Data
        #else
        // iOS: simplified text-based PDF
        let renderer = UIGraphicsPDFRenderer(bounds: CGRect(x: 0, y: 0, width: pageWidth, height: pageHeight))
        let data = renderer.pdfData { ctx in
            ctx.beginPage()
            let attrs: [NSAttributedString.Key: Any] = [
                .font: UIFont.systemFont(ofSize: 20, weight: .bold)
            ]
            title.draw(at: CGPoint(x: margin, y: margin), withAttributes: attrs)
        }
        return data
        #endif
    }

    #if os(macOS)
    private static func drawText(
        context: CGContext,
        text: String,
        x: CGFloat,
        y: CGFloat,
        width: CGFloat,
        font: NSFont,
        color: NSColor,
        alignment: NSTextAlignment
    ) {
        let paragraphStyle = NSMutableParagraphStyle()
        paragraphStyle.alignment = alignment
        paragraphStyle.lineBreakMode = .byWordWrapping

        let attributes: [NSAttributedString.Key: Any] = [
            .font: font,
            .foregroundColor: color,
            .paragraphStyle: paragraphStyle
        ]
        let attrString = NSAttributedString(string: text, attributes: attributes)
        let framesetter = CTFramesetterCreateWithAttributedString(attrString as CFAttributedString)
        let path = CGPath(rect: CGRect(x: x, y: y - 30, width: width, height: 30), transform: nil)
        let frame = CTFramesetterCreateFrame(framesetter, CFRangeMake(0, attrString.length), path, nil)

        context.saveGState()
        CTFrameDraw(frame, context)
        context.restoreGState()
    }
    #endif

    private static func sectionContent(_ sectionName: String, emails: [MBOXParser.RawEmail]) -> String {
        switch sectionName {
        case "Executive Summary":
            return buildExecutiveSummary(emails: emails)
        case "Email Volume Statistics":
            return buildVolumeStats(emails: emails)
        case "Top Contacts":
            return buildTopContacts(emails: emails)
        case "Sentiment Analysis":
            return buildSentimentAnalysis(emails: emails)
        case "Category Distribution":
            return buildCategoryDistribution(emails: emails)
        case "Timeline Visualization":
            return buildTimeline(emails: emails)
        case "Security Findings":
            return buildSecurityFindings(emails: emails)
        case "Anomaly Detection Results":
            return buildAnomalyResults(emails: emails)
        case "Attachment Overview":
            return buildAttachmentOverview(emails: emails)
        default:
            return "No data available for this section."
        }
    }

    private static func buildExecutiveSummary(emails: [MBOXParser.RawEmail]) -> String {
        let total = emails.count
        let sent = emails.filter { $0.messageType.lowercased() == "sent" }.count
        let received = total - sent
        let withAttachments = emails.filter { !$0.attachments.isEmpty }.count
        var contacts = Set<String>()
        for email in emails {
            if let from = email.headers["From"] {
                contacts.insert(from.lowercased())
            }
        }
        return """
        **Overview**
        Total Emails: \(total)
        Sent: \(sent)
        Received: \(received)
        Unique Contacts: \(contacts.count)
        Emails with Attachments: \(withAttachments)

        This report provides a comprehensive analysis of the email archive,
        covering volume trends, sentiment patterns, contact networks, and
        security observations.
        """
    }

    private static func buildVolumeStats(emails: [MBOXParser.RawEmail]) -> String {
        let datedEmails = emails.compactMap { email -> (MBOXParser.RawEmail, Date)? in
            guard let date = MBOXParser.parseDate(email.headers["Date"]) else { return nil }
            return (email, date)
        }.sorted { $0.1 < $1.1 }

        guard let first = datedEmails.first, let last = datedEmails.last else {
            return "No date information available."
        }
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        let daySpan = max(1, Calendar.current.dateComponents([.day], from: first.1, to: last.1).day ?? 1)
        let avgPerDay = Double(emails.count) / Double(daySpan)

        return """
        **Email Volume Statistics**
        Date Range: \(formatter.string(from: first.1)) to \(formatter.string(from: last.1))
        Total Days: \(daySpan)
        Total Emails: \(emails.count)
        Average per Day: \(String(format: "%.1f", avgPerDay))
        """
    }

    private static func buildTopContacts(emails: [MBOXParser.RawEmail]) -> String {
        var counts: [String: Int] = [:]
        for email in emails {
            if let from = email.headers["From"] {
                counts[from, default: 0] += 1
            }
        }
        let sorted = counts.sorted { $0.value > $1.value }.prefix(10)
        var text = "**Top 10 Contacts by Email Count**\n"
        for (index, entry) in sorted.enumerated() {
            text += "\(index + 1). \(entry.key): \(entry.value) emails\n"
        }
        return text
    }

    private static func buildSentimentAnalysis(emails: [MBOXParser.RawEmail]) -> String {
        let tagger = NLTagger(tagSchemes: [.sentimentScore])
        var positive = 0, negative = 0, neutral = 0
        var total = 0.0
        var count = 0

        for email in emails {
            let text = bodyTextForReport(email)
            guard !text.isEmpty else { continue }
            tagger.string = text
            let (tag, _) = tagger.tag(at: text.startIndex, unit: .paragraph, scheme: .sentimentScore)
            if let raw = tag?.rawValue, let score = Double(raw) {
                total += score
                count += 1
                if score > 0.4 { positive += 1 }
                else if score < -0.4 { negative += 1 }
                else { neutral += 1 }
            }
        }
        let avg = count > 0 ? total / Double(count) : 0

        return """
        **Sentiment Analysis Summary**
        Emails Analyzed: \(count)
        Average Sentiment Score: \(String(format: "%.3f", avg))
        Positive: \(positive)
        Neutral: \(neutral)
        Negative: \(negative)
        """
    }

    private static func buildCategoryDistribution(emails: [MBOXParser.RawEmail]) -> String {
        var counts: [String: Int] = [:]
        for email in emails {
            let cat = email.messageType.isEmpty ? "Unknown" : email.messageType.capitalized
            counts[cat, default: 0] += 1
        }
        var text = "**Category Distribution**\n"
        for (cat, count) in counts.sorted(by: { $0.value > $1.value }) {
            text += "\(cat): \(count) emails\n"
        }
        return text
    }

    private static func buildTimeline(emails: [MBOXParser.RawEmail]) -> String {
        var monthlyCounts: [String: Int] = [:]
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM"

        for email in emails {
            if let date = MBOXParser.parseDate(email.headers["Date"]) {
                let key = formatter.string(from: date)
                monthlyCounts[key, default: 0] += 1
            }
        }

        var text = "**Monthly Email Volume**\n"
        for (month, count) in monthlyCounts.sorted(by: { $0.key < $1.key }) {
            text += "\(month): \(count) emails\n"
        }
        return text
    }

    private static func buildSecurityFindings(emails: [MBOXParser.RawEmail]) -> String {
        var spoofCount = 0
        var noAuthCount = 0
        for email in emails {
            let anomalies = email.anomalies.joined(separator: " ").lowercased()
            if anomalies.contains("spoof") || anomalies.contains("spf") || anomalies.contains("dkim") {
                spoofCount += 1
            }
            if anomalies.contains("auth") {
                noAuthCount += 1
            }
        }
        let anomalyCount = emails.filter { !$0.anomalies.isEmpty }.count

        return """
        **Security Findings**
        Emails with Anomalies: \(anomalyCount)
        Potential Spoofing: \(spoofCount)
        Authentication Issues: \(noAuthCount)
        """
    }

    private static func buildAnomalyResults(emails: [MBOXParser.RawEmail]) -> String {
        let anomalyEmails = emails.filter { !$0.anomalies.isEmpty }
        var text = "**Anomaly Detection Results**\n"
        text += "Emails with anomalies: \(anomalyEmails.count) of \(emails.count)\n\n"

        var categorized: [String: Int] = [:]
        for email in anomalyEmails {
            for anomaly in email.anomalies {
                categorized[anomaly, default: 0] += 1
            }
        }
        for (type, count) in categorized.sorted(by: { $0.value > $1.value }).prefix(10) {
            text += "\(type): \(count)\n"
        }
        return text
    }

    private static func buildAttachmentOverview(emails: [MBOXParser.RawEmail]) -> String {
        let withAttachments = emails.filter { !$0.attachments.isEmpty }
        var typeCounts: [String: Int] = [:]
        var totalSize = 0
        for email in withAttachments {
            for att in email.attachments {
                let ext = (att.filename as NSString).pathExtension.lowercased()
                let key = ext.isEmpty ? att.mimeType : ".\(ext)"
                typeCounts[key, default: 0] += 1
                totalSize += att.size
            }
        }
        var text = """
        **Attachment Overview**
        Emails with Attachments: \(withAttachments.count)
        Total Attachment Size: \(String(format: "%.1f MB", Double(totalSize) / 1_048_576))

        **Attachment Types**
        """
        for (type, count) in typeCounts.sorted(by: { $0.value > $1.value }).prefix(10) {
            text += "\n\(type): \(count)"
        }
        return text
    }

    private static func bodyTextForReport(_ email: MBOXParser.RawEmail) -> String {
        if !email.plainBody.isEmpty { return String(email.plainBody.prefix(2000)) }
        if !email.htmlBody.isEmpty {
            return String(email.htmlBody
                .replacingOccurrences(of: "<[^>]+>", with: " ", options: .regularExpression)
                .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
                .trimmingCharacters(in: .whitespacesAndNewlines)
                .prefix(2000))
        }
        return ""
    }
}

// MARK: - Report Builder View

struct ReportBuilderView: View {
    // v2: bounded working set from the store (no injected corpus).
    @State private var workingSet: [MBOXParser.RawEmail] = []
    @State private var archiveTotal = 0
    var isPresented: Binding<Bool>?
    @Environment(\.dismiss) private var envDismiss

    @State private var reportTitle = "Email Archive Report"
    @State private var authorName = ""
    @State private var dateFrom = Calendar.current.date(byAdding: .year, value: -1, to: Date()) ?? Date()
    @State private var dateTo = Date()
    @State private var useDateRange = false
    @State private var sections: [ReportSection] = Self.defaultSections
    @State private var isGenerating = false
    @State private var generatedPDF: Data?
    @State private var showSaveSuccess = false
    @State private var saveError: String?

    private static let defaultSections: [ReportSection] = [
        ReportSection(name: "Executive Summary", icon: "doc.text.fill", isEnabled: true),
        ReportSection(name: "Email Volume Statistics", icon: "chart.bar.fill", isEnabled: true),
        ReportSection(name: "Top Contacts", icon: "person.2.fill", isEnabled: true),
        ReportSection(name: "Sentiment Analysis", icon: "heart.fill", isEnabled: true),
        ReportSection(name: "Category Distribution", icon: "chart.pie.fill", isEnabled: true),
        ReportSection(name: "Timeline Visualization", icon: "calendar", isEnabled: true),
        ReportSection(name: "Security Findings", icon: "lock.shield", isEnabled: true),
        ReportSection(name: "Anomaly Detection Results", icon: "exclamationmark.triangle", isEnabled: true),
        ReportSection(name: "Attachment Overview", icon: "paperclip", isEnabled: false),
    ]

    var body: some View {
        VStack(spacing: 0) {
            headerBar
            Divider()

            #if os(macOS)
            HSplitView {
                configPanel
                    .frame(minWidth: 300, idealWidth: 350)
                previewPanel
                    .frame(minWidth: 250, idealWidth: 300)
            }
            #else
            HStack(spacing: 0) {
                configPanel
                previewPanel
            }
            #endif
        }
        #if os(macOS)
        .frame(minWidth: 480, minHeight: 380)
        #endif
        .background(AppColors.backgroundTertiary)
        .alert("Export Failed", isPresented: Binding(get: { saveError != nil }, set: { if !$0 { saveError = nil } })) {
            Button("OK") { saveError = nil }
        } message: {
            Text(saveError ?? "An unknown error occurred.")
        }
        .alert("Report Saved", isPresented: $showSaveSuccess) {
            Button("OK") {}
        } message: {
            Text("The PDF report has been saved successfully.")
        }
    }

    // MARK: - Header

    private var headerBar: some View {
        HStack {
            HStack(spacing: Spacing.xSmall) {
                Image(systemName: "doc.richtext")
                    .font(.title2)
                    .adaptiveIconGradient(colors: [.orange, .red])
                VStack(alignment: .leading, spacing: 2) {
                    Text("Report Builder")
                        .font(Typography.headline)
                    Text("\(archiveTotal) emails available")
                        .font(Typography.caption1)
                        .foregroundColor(AppColors.secondary)
                        .task { archiveTotal = (try? await ArchiveDataService.shared.count()) ?? 0 }
                }
            }
            Spacer()

            if isGenerating {
                ProgressView()
                    .scaleEffect(0.7)
                    .padding(.trailing, Spacing.xSmall)
            }

            if isPresented != nil {
                Button("Done") { closeSheet() }
                    .keyboardShortcut(.cancelAction)
            }
        }
        .padding(.horizontal, Spacing.medium)
        .padding(.vertical, Spacing.small)
        .background(AppColors.backgroundPrimary)
    }

    private func closeSheet() {
        if let isPresented { isPresented.wrappedValue = false } else { envDismiss() }
    }

    // MARK: - Config Panel

    private var configPanel: some View {
        ScrollView {
            VStack(alignment: .leading, spacing: Spacing.medium) {
                // Report Title
                VStack(alignment: .leading, spacing: Spacing.xxSmall) {
                    Text("Report Title")
                        .font(Typography.subheadline)
                        .fontWeight(.semibold)
                    TextField("Enter report title", text: $reportTitle)
                        .textFieldStyle(.roundedBorder)
                }

                // Author
                VStack(alignment: .leading, spacing: Spacing.xxSmall) {
                    Text("Author")
                        .font(Typography.subheadline)
                        .fontWeight(.semibold)
                    TextField("Enter author name", text: $authorName)
                        .textFieldStyle(.roundedBorder)
                }

                // Date Range
                VStack(alignment: .leading, spacing: Spacing.xxSmall) {
                    Toggle("Filter by Date Range", isOn: $useDateRange)
                        .font(Typography.subheadline)
                        .fontWeight(.semibold)

                    if useDateRange {
                        HStack {
                            DatePicker("From", selection: $dateFrom, displayedComponents: .date)
                                .labelsHidden()
                            Text("to")
                                .font(Typography.caption1)
                                .foregroundColor(AppColors.secondary)
                            DatePicker("To", selection: $dateTo, displayedComponents: .date)
                                .labelsHidden()
                        }
                    }
                }

                Divider()

                // Sections
                VStack(alignment: .leading, spacing: Spacing.xSmall) {
                    Text("Report Sections")
                        .font(Typography.subheadline)
                        .fontWeight(.semibold)

                    ForEach($sections) { $section in
                        HStack(spacing: Spacing.xSmall) {
                            Toggle(isOn: $section.isEnabled) {
                                HStack(spacing: Spacing.xSmall) {
                                    Image(systemName: section.icon)
                                        .foregroundColor(section.isEnabled ? AppColors.primary : AppColors.secondary)
                                        .frame(width: 20)
                                    Text(section.name)
                                        .font(Typography.callout)
                                }
                            }
                            #if os(macOS)
                            .toggleStyle(.checkbox)
                            #endif
                        }
                        .padding(.vertical, Spacing.xxxSmall)
                    }
                }

                Divider()

                // Generate Button
                Button {
                    generateReport()
                } label: {
                    HStack {
                        Image(systemName: "doc.badge.plus")
                        Text("Generate PDF Report")
                    }
                }
                .buttonStyle(PrimaryButtonStyle())
                .disabled(isGenerating || reportTitle.isEmpty)

                // Save Button
                if generatedPDF != nil {
                    Button {
                        saveReport()
                    } label: {
                        HStack {
                            Image(systemName: "square.and.arrow.down")
                            Text("Save PDF")
                        }
                    }
                    .buttonStyle(SecondaryButtonStyle())
                }
            }
            .padding(Spacing.medium)
        }
    }

    // MARK: - Preview Panel

    private var previewPanel: some View {
        VStack(alignment: .leading, spacing: Spacing.small) {
            Text("Preview")
                .font(Typography.headline)
                .padding(.horizontal, Spacing.medium)
                .padding(.top, Spacing.medium)

            ScrollView {
                VStack(alignment: .leading, spacing: Spacing.small) {
                    // Title preview
                    VStack(alignment: .leading, spacing: Spacing.xxSmall) {
                        Text(reportTitle.isEmpty ? "Untitled Report" : reportTitle)
                            .font(Typography.title3)
                            .fontWeight(.bold)
                        if !authorName.isEmpty {
                            Text("by \(authorName)")
                                .font(Typography.caption1)
                                .foregroundColor(AppColors.secondary)
                        }
                        if useDateRange {
                            Text("\(formattedDate(dateFrom)) - \(formattedDate(dateTo))")
                                .font(Typography.caption2)
                                .foregroundColor(AppColors.secondary)
                        }
                    }
                    .padding(Spacing.small)
                    .frame(maxWidth: .infinity, alignment: .leading)
                    .adaptiveCard(cornerRadius: CornerRadius.medium)

                    Divider()

                    Text("Included Sections")
                        .font(Typography.subheadline)
                        .fontWeight(.semibold)

                    let enabled = sections.filter(\.isEnabled)
                    if enabled.isEmpty {
                        Text("No sections selected")
                            .font(Typography.caption1)
                            .foregroundColor(AppColors.secondary)
                    } else {
                        ForEach(Array(enabled.enumerated()), id: \.element.id) { index, section in
                            HStack(spacing: Spacing.xSmall) {
                                Text("\(index + 1)")
                                    .font(Typography.caption2)
                                    .fontWeight(.bold)
                                    .foregroundColor(.white)
                                    .frame(width: 20, height: 20)
                                    .background(AppColors.primary)
                                    .clipShape(Circle())
                                Image(systemName: section.icon)
                                    .foregroundColor(AppColors.primary)
                                    .frame(width: 16)
                                Text(section.name)
                                    .font(Typography.caption1)
                            }
                        }
                    }

                    if generatedPDF != nil {
                        Divider()
                        HStack {
                            Image(systemName: "checkmark.circle.fill")
                                .foregroundColor(AppColors.success)
                            Text("PDF generated successfully")
                                .font(Typography.caption1)
                                .foregroundColor(AppColors.success)
                        }
                    }
                }
                .padding(Spacing.medium)
            }
        }
        .background(AppColors.backgroundSecondary)
    }

    // MARK: - Actions

    private func generateReport() {
        isGenerating = true
        let title = reportTitle
        let author = authorName
        let sectionsCopy = sections
        let range: ClosedRange<Date>? = useDateRange ? dateFrom...dateTo : nil

        Task.detached {
            // Bounded working set from the store (report covers up to 5000 recent).
            var emailsCopy: [MBOXParser.RawEmail] = []
            let stream = await ArchiveDataService.shared.streamFullEmails(query: .all, batchSize: 200)
            do { for try await b in stream { emailsCopy.append(contentsOf: b); if emailsCopy.count >= 5000 { break } } } catch { }
            emailsCopy = Array(emailsCopy.prefix(5000))
            let pdf = ReportGenerator.generatePDF(
                title: title,
                author: author,
                sections: sectionsCopy,
                emails: emailsCopy,
                dateRange: range
            )
            await MainActor.run {
                generatedPDF = pdf
                isGenerating = false
            }
        }
    }

    private func saveReport() {
        #if os(macOS)
        guard let pdf = generatedPDF else { return }
        let panel = NSSavePanel()
        panel.allowedContentTypes = [.pdf]
        panel.nameFieldStringValue = "\(reportTitle).pdf"
        let response = panel.runModal()
        guard response == .OK, let url = panel.url else { return }
        do {
            try pdf.write(to: url, options: .atomic)
            showSaveSuccess = true
        } catch {
            saveError = error.localizedDescription
        }
        #endif
    }

    private func formattedDate(_ date: Date) -> String {
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        return formatter.string(from: date)
    }
}
