//
//  ReviewDashboardView.swift
//  maxmailin
//
//  The legal reviewer's morning surface: what's assigned, how fast review
//  is moving, when it finishes at this pace — and whether the privilege
//  log is complete (a privileged email WITHOUT an annotation is the hole
//  opposing counsel finds). One click copies the defensibility summary.
//

import SwiftUI

// MARK: - Pure progress model (unit-tested)

enum ReviewProgressModel {

    struct BatchProgress: Identifiable {
        let id: UUID
        let name: String
        let total: Int
        let reviewed: Int
        let skipped: Int
        var pending: Int { total - reviewed - skipped }
        var fraction: Double { total == 0 ? 0 : Double(reviewed + skipped) / Double(total) }
    }

    struct Summary {
        var batches: [BatchProgress] = []
        var totalAssigned = 0
        var totalReviewed = 0
        var totalSkipped = 0
        var reviewDays = 0                 // distinct days with review activity
        var velocityPerDay: Double = 0     // reviewed emails / active day
        var estimatedDaysRemaining: Double? = nil
        var privilegedTotal = 0
        var privilegedMissingAnnotation: [UUID] = []
        var pending: Int { totalAssigned - totalReviewed - totalSkipped }
        var privilegeLogComplete: Bool { privilegedMissingAnnotation.isEmpty }
    }

    /// All inputs are plain values so this is testable without singletons.
    static func summarize(
        batches: [(id: UUID, name: String, emailIDs: [UUID], reviewed: Set<UUID>, skipped: Set<UUID>)],
        reviewActivityDays: Set<String>,          // e.g. "2026-08-09" — days with review audit entries
        privilegedIDs: [UUID],
        annotatedIDs: Set<UUID>
    ) -> Summary {
        var summary = Summary()
        for batch in batches {
            let progress = BatchProgress(
                id: batch.id, name: batch.name,
                total: batch.emailIDs.count,
                reviewed: batch.reviewed.count,
                skipped: batch.skipped.count)
            summary.batches.append(progress)
            summary.totalAssigned += progress.total
            summary.totalReviewed += progress.reviewed
            summary.totalSkipped += progress.skipped
        }
        summary.reviewDays = reviewActivityDays.count
        if summary.reviewDays > 0 {
            summary.velocityPerDay = Double(summary.totalReviewed) / Double(summary.reviewDays)
            if summary.velocityPerDay > 0 {
                summary.estimatedDaysRemaining = Double(summary.pending) / summary.velocityPerDay
            }
        }
        summary.privilegedTotal = privilegedIDs.count
        summary.privilegedMissingAnnotation = privilegedIDs.filter { !annotatedIDs.contains($0) }
        return summary
    }

    /// The defensibility numbers as plain text for the production record.
    static func defensibilityReport(_ s: Summary, caseNumber: String, examiner: String,
                                    documentNumber: String? = nil) -> String {
        var out = "REVIEW DEFENSIBILITY SUMMARY\n"
        out += "============================\n"
        if let doc = documentNumber { out += "Document:  \(doc)\n" }
        out += "Case:      \(caseNumber.isEmpty ? "(no case number set)" : caseNumber)\n"
        out += "Reviewer:  \(examiner.isEmpty ? "(not set)" : examiner)\n\n"
        out += "Assigned:  \(s.totalAssigned) emails in \(s.batches.count) batch(es)\n"
        out += "Reviewed:  \(s.totalReviewed)   Skipped: \(s.totalSkipped)   Pending: \(s.pending)\n"
        if s.reviewDays > 0 {
            out += "Velocity:  \(String(format: "%.1f", s.velocityPerDay)) emails/day over \(s.reviewDays) active day(s)\n"
        }
        if let eta = s.estimatedDaysRemaining {
            out += "Estimated completion: \(String(format: "%.1f", eta)) more day(s) at this pace\n"
        }
        out += "\nPRIVILEGE LOG\n"
        out += "Privileged-coded emails: \(s.privilegedTotal)\n"
        if s.privilegeLogComplete {
            out += "Every privileged email carries an annotation — the log is complete.\n"
        } else {
            out += "WARNING: \(s.privilegedMissingAnnotation.count) privileged email(s) have NO annotation — the log is incomplete.\n"
        }
        out += "\nPer batch:\n"
        for batch in s.batches {
            out += "  \(batch.name): \(batch.reviewed)/\(batch.total) reviewed"
            if batch.skipped > 0 { out += ", \(batch.skipped) skipped" }
            out += "\n"
        }
        out += "\nGenerated by mailin — single-reviewer record from this Mac.\n"
        return out
    }
}

// MARK: - View

struct ReviewDashboardView: View {
    var onClose: (() -> Void)? = nil

    @Environment(\.dismiss) private var dismiss
    @ObservedObject private var batchManager = ReviewBatchManager.shared
    @ObservedObject private var forensicManager = ForensicManager.shared
    @State private var summary = ReviewProgressModel.Summary()
    @State private var copied = false

    var body: some View {
        VStack(alignment: .leading, spacing: 0) {
            HStack {
                VStack(alignment: .leading, spacing: Spacing.xxxSmall) {
                    Label("Review Dashboard", systemImage: "chart.bar.doc.horizontal")
                        .font(Typography.title2)
                    Text("Assignment, pace, and privilege-log completeness — the defensibility numbers in one place")
                        .font(Typography.caption1)
                        .foregroundColor(AppColors.secondary)
                }
                Spacer()
                HelpDot(text: "Batches come from Review Batches; velocity counts reviewed emails per active day (days with review actions in the audit trail). The privilege-log check lists privileged-coded emails that still lack an annotation — complete those before production.")
                Button {
                    let snapshot = summary
                    Task { @MainActor in
                        let number = await DocumentRegistry.post(
                            .report, summary: "Defensibility summary — \(snapshot.totalReviewed)/\(snapshot.totalAssigned) reviewed")
                        PlatformClipboard.copyString(ReviewProgressModel.defensibilityReport(
                            snapshot, caseNumber: forensicManager.caseNumber,
                            examiner: forensicManager.examinerName,
                            documentNumber: number))
                        copied = true
                    }
                } label: {
                    Label(copied ? "Copied" : "Copy Defensibility Summary", systemImage: "doc.on.doc")
                }
                .help("The production-ready numbers: assignment, velocity, and privilege-log status as plain text")
                Button { if let onClose { onClose() } else { dismiss() } } label: {
                    Image(systemName: "xmark.circle.fill")
                        .foregroundColor(AppColors.secondary)
                        .imageScale(.large)
                }
                .buttonStyle(.plain)
                .help("Close")
                .accessibilityLabel("Close review dashboard")
            }
            .padding(Spacing.medium)
            Divider()

            if summary.totalAssigned == 0 {
                VStack(spacing: Spacing.small) {
                    Spacer()
                    Image(systemName: "rectangle.stack.badge.play")
                        .font(.largeTitle).foregroundColor(AppColors.secondary)
                    Text("No review batches yet — create them from Review Batches (Tools) to start tracking progress.")
                        .font(Typography.callout)
                        .foregroundColor(AppColors.secondary)
                        .multilineTextAlignment(.center)
                    Spacer()
                }
                .frame(maxWidth: .infinity)
            } else {
                List {
                    Section {
                        statRow
                    }
                    Section("Batches") {
                        ForEach(summary.batches) { batch in
                            HStack {
                                Text(batch.name)
                                    .font(Typography.callout)
                                ProgressView(value: batch.fraction)
                                    .frame(maxWidth: 220)
                                Spacer()
                                Text("\(batch.reviewed)/\(batch.total)\(batch.skipped > 0 ? " (+\(batch.skipped) skipped)" : "")")
                                    .font(Typography.caption1)
                                    .foregroundColor(AppColors.secondary)
                            }
                        }
                    }
                    Section {
                        if summary.privilegedTotal == 0 {
                            Label("No emails coded Privileged yet.", systemImage: "lock.shield")
                                .foregroundColor(AppColors.secondary)
                        } else if summary.privilegeLogComplete {
                            Label("Privilege log complete — all \(summary.privilegedTotal) privileged emails are annotated.",
                                  systemImage: "checkmark.seal.fill")
                                .foregroundColor(.green)
                        } else {
                            Label("\(summary.privilegedMissingAnnotation.count) of \(summary.privilegedTotal) privileged emails have NO annotation — complete these before production.",
                                  systemImage: "exclamationmark.triangle.fill")
                                .foregroundColor(.red)
                        }
                    } header: {
                        Text("Privilege log")
                    } footer: {
                        Text("Every withheld email needs a reason on record; an unannotated privileged email is the gap opposing counsel will ask about.")
                            .font(Typography.caption2)
                    }
                }
            }
        }
        .toolWindowFrame()
        .task { rebuild() }
        .onReceive(batchManager.$batches) { _ in rebuild() }
    }

    private var statRow: some View {
        HStack(spacing: Spacing.medium) {
            stat("Assigned", "\(summary.totalAssigned)")
            stat("Reviewed", "\(summary.totalReviewed)")
            stat("Pending", "\(summary.pending)")
            stat("Velocity", summary.reviewDays > 0
                 ? String(format: "%.0f/day", summary.velocityPerDay) : "—")
            stat("Est. finish", summary.estimatedDaysRemaining.map {
                String(format: "%.1f days", $0) } ?? "—")
        }
        .frame(maxWidth: .infinity)
    }

    private func stat(_ title: String, _ value: String) -> some View {
        VStack(spacing: 2) {
            Text(value)
                .font(Typography.title3)
                .fontWeight(.bold)
            Text(title)
                .font(Typography.caption2)
                .foregroundColor(AppColors.secondary)
        }
        .frame(maxWidth: .infinity)
    }

    private func rebuild() {
        // Active days = distinct days with review-ish audit actions.
        let dayFmt = DateFormatter()
        dayFmt.dateFormat = "yyyy-MM-dd"
        let reviewActions = forensicManager.auditLog.filter {
            $0.action.localizedCaseInsensitiveContains("review")
                || $0.action.localizedCaseInsensitiveContains("tag")
                || $0.action.localizedCaseInsensitiveContains("annotat")
        }
        let activeDays = Set(reviewActions.map { dayFmt.string(from: $0.timestamp) })

        let privilegedIDs = forensicManager.evidenceTags
            .filter { $0.value == .privileged }.map(\.key)
        let annotatedIDs = Set(forensicManager.annotations.keys)

        summary = ReviewProgressModel.summarize(
            batches: batchManager.batches.map {
                ($0.id, $0.name, $0.emailIDs, $0.reviewedIDs, $0.skippedIDs)
            },
            reviewActivityDays: activeDays,
            privilegedIDs: privilegedIDs,
            annotatedIDs: annotatedIDs)
    }
}
