//
//  StoryFileBuilder.swift
//  maxmailin
//
//  The journalist's deliverable: every annotated email becomes a cited
//  finding in one Markdown document — the answer to "how do you know
//  this?" for editors and lawyers. Claims are your annotations; each
//  carries its source email (sender, date, subject, Message-ID) as the
//  citation. Pure builder, unit-tested.
//

import Foundation

enum StoryFileBuilder {

    struct Finding {
        let claim: String            // the annotation text
        let claimDate: Date          // when the annotation was made
        let subject: String
        let from: String
        let sentDate: String         // email's own date header, verbatim
        let messageID: String?
        let evidenceTag: String?     // e.g. Relevant/Flagged, if coded
    }

    /// Markdown story file: title block, findings with citations, source
    /// index. Findings are ordered by when the researcher recorded them —
    /// the investigation's own narrative order.
    static func markdown(title: String, author: String, findings: [Finding],
                         documentNumber: String? = nil) -> String {
        let fmt = DateFormatter()
        fmt.dateStyle = .medium
        var out = "# \(title.isEmpty ? "Story File" : title)\n\n"
        if !author.isEmpty { out += "*Researched by \(author)*\n\n" }
        if let doc = documentNumber { out += "*Version \(doc)*\n\n" }
        out += "> \(findings.count) finding(s), each cited to its source email. "
        out += "Generated by mailin from a local archive — sources verifiable against the originals.\n\n"

        if findings.isEmpty {
            out += "_No findings yet. Annotate emails during research; every annotation becomes a cited finding here._\n"
            return out
        }

        out += "## Findings\n\n"
        let ordered = findings.sorted { $0.claimDate < $1.claimDate }
        for (index, finding) in ordered.enumerated() {
            out += "### \(index + 1). \(finding.claim)\n\n"
            out += "> **Source:** “\(finding.subject)” — \(finding.from), \(finding.sentDate)"
            if let tag = finding.evidenceTag { out += " · coded \(tag)" }
            out += "\n"
            if let mid = finding.messageID {
                out += ">\n> `\(mid)`\n"
            }
            out += "\n"
        }

        out += "## Source Index\n\n"
        for (index, finding) in ordered.enumerated() {
            out += "\(index + 1). \(finding.from) — “\(finding.subject)” (\(finding.sentDate))\n"
        }
        return out
    }
}
